@file:Suppress("NOTHING_TO_INLINE", "DEPRECATION")

package cn.apisium.sarla.nodes

import cn.apisium.sarla.*
import cn.apisium.sarla.dom.*

@SarlaDsl
expect open class DataNodeBlock: NodeBlock {
    operator fun <T: Any> Data<T>.get(key: Any): Data<T>
    operator fun <T: Any> Data<T>.invoke(): T

    //inline operator fun Data<*>.get(key: Any): Data<*>
    //inline operator fun Data<*>.invoke(): Any
    inline operator fun <T: Number> Data<T>.plus(value: T): T

    inline operator fun <T: Number> Data<T>.unaryPlus()
}

@SarlaDsl
expect open class NodeBlock {
    inline operator fun String.unaryPlus()

    inline operator fun Number.unaryPlus()

    inline operator fun Nothing.unaryPlus()

    inline operator fun Unit.unaryPlus()

    inline operator fun <P, T: SarlaProp<P>> SarlaInstant<T>.invoke(props: P? = null, noinline block: Nodes? = null)
    inline operator fun <T: Sarla> SarlaInstant<T>.invoke(noinline block: Nodes? = null)
    inline operator fun <P, T: SarlaProp<P>> SarlaInstant<T>.invoke(void: Int, props: P? = null, noinline block: DataNodes? = null)
    inline operator fun <T: Sarla> SarlaInstant<T>.invoke(void: Int, noinline block: DataNodes? = null)


    inline operator fun <P, T: SarlaProp<P>> SarlaInlineInstant<T>.invoke(props: P? = null, noinline block: Nodes? = null)
    inline operator fun <T: Sarla> SarlaInlineInstant<T>.invoke(noinline block: Nodes? = null)
    inline operator fun <P, T: SarlaProp<P>> SarlaInlineInstant<T>.invoke(void: Int, props: P? = null, noinline block: DataNodes? = null)
    inline operator fun <T: Sarla> SarlaInlineInstant<T>.invoke(void: Int, noinline block: DataNodes? = null)

    inline fun tag(void: Int, name: String, className: String? = null, noinline block: DataNodes? = null)
    inline fun tag(void: Int, name: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun tag(void: Int, name: String, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun tag(name: String, className: String? = null, block: Nodes)
    inline fun tag(name: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun tag(name: String, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun tag(name: String, className: String? = null)

    inline fun a(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun address(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun area(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun article(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun aside(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun audio(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun b(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun base(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun bdi(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun bdo(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun big(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun blockquote(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun body(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun br(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun button(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun canvas(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun caption(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun cite(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun code(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun col(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun colgroup(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun data(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun datalist(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun dd(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun del(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun details(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun dfn(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun dialog(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun div(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun dl(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun dt(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun em(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun embed(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun fieldset(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun figcaption(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun figure(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun footer(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun form(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun h1(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun h2(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun h3(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun h4(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun h5(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun h6(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun head(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun header(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun hgroup(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun hr(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun html(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun i(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun iframe(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun img(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun input(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun ins(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun kbd(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun keygen(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun label(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun legend(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun li(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun link(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun main(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun map(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun mark(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun menu(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun menuitem(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun meta(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun meter(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun nav(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun noscript(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun objectElement(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun ol(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun optgroup(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun option(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun output(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun p(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun param(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun picture(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun pre(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun progress(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun q(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun rp(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun rt(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun ruby(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun s(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun samp(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun script(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun section(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun select(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun small(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun source(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun span(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun strong(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun styleElement(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun sub(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun summary(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun sup(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun table(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun tbody(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun td(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun textarea(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun tfoot(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun th(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun thead(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun time(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun title(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun tr(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun track(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun u(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun ul(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun varElement(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun video(void: Int, className: String? = null, noinline block: DataNodes? = null)
    inline fun wbr(void: Int, className: String? = null, noinline block: DataNodes? = null)

    inline fun a(void: Int, attr: Attr<AnchorHTMLAttributes<HTMLAnchorElement>>, noinline block: DataNodes? = null)
    inline fun address(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun area(void: Int, attr: Attr<AreaHTMLAttributes<HTMLAreaElement>>, noinline block: DataNodes? = null)
    inline fun article(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun aside(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun audio(void: Int, attr: Attr<AudioHTMLAttributes<HTMLAudioElement>>, noinline block: DataNodes? = null)
    inline fun b(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun base(void: Int, attr: Attr<BaseHTMLAttributes<HTMLBaseElement>>, noinline block: DataNodes? = null)
    inline fun bdi(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun bdo(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun big(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun blockquote(void: Int, attr: Attr<BlockquoteHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun body(void: Int, attr: Attr<HTMLAttributes<HTMLBodyElement>>, noinline block: DataNodes? = null)
    inline fun br(void: Int, attr: Attr<HTMLAttributes<HTMLBRElement>>, noinline block: DataNodes? = null)
    inline fun button(void: Int, attr: Attr<ButtonHTMLAttributes<HTMLButtonElement>>, noinline block: DataNodes? = null)
    inline fun canvas(void: Int, attr: Attr<CanvasHTMLAttributes<HTMLCanvasElement>>, noinline block: DataNodes? = null)
    inline fun caption(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun cite(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun code(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun col(void: Int, attr: Attr<ColHTMLAttributes<HTMLTableColElement>>, noinline block: DataNodes? = null)
    inline fun colgroup(void: Int, attr: Attr<ColgroupHTMLAttributes<HTMLTableColElement>>, noinline block: DataNodes? = null)
    inline fun data(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun datalist(void: Int, attr: Attr<HTMLAttributes<HTMLDataListElement>>, noinline block: DataNodes? = null)
    inline fun dd(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun del(void: Int, attr: Attr<DelHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun details(void: Int, attr: Attr<DetailsHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun dfn(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun dialog(void: Int, attr: Attr<DialogHTMLAttributes<HTMLDialogElement>>, noinline block: DataNodes? = null)
    inline fun div(void: Int, attr: Attr<HTMLAttributes<HTMLDivElement>>, noinline block: DataNodes? = null)
    inline fun dl(void: Int, attr: Attr<HTMLAttributes<HTMLDListElement>>, noinline block: DataNodes? = null)
    inline fun dt(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun em(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun embed(void: Int, attr: Attr<EmbedHTMLAttributes<HTMLEmbedElement>>, noinline block: DataNodes? = null)
    inline fun fieldset(void: Int, attr: Attr<FieldsetHTMLAttributes<HTMLFieldSetElement>>, noinline block: DataNodes? = null)
    inline fun figcaption(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun figure(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun footer(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun form(void: Int, attr: Attr<FormHTMLAttributes<HTMLFormElement>>, noinline block: DataNodes? = null)
    inline fun h1(void: Int, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun h2(void: Int, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun h3(void: Int, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun h4(void: Int, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun h5(void: Int, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun h6(void: Int, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun head(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun header(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun hgroup(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun hr(void: Int, attr: Attr<HTMLAttributes<HTMLHRElement>>, noinline block: DataNodes? = null)
    inline fun html(void: Int, attr: Attr<HtmlHTMLAttributes<HTMLHtmlElement>>, noinline block: DataNodes? = null)
    inline fun i(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun iframe(void: Int, attr: Attr<IframeHTMLAttributes<HTMLIFrameElement>>, noinline block: DataNodes? = null)
    inline fun img(void: Int, attr: Attr<ImgHTMLAttributes<HTMLImageElement>>, noinline block: DataNodes? = null)
    inline fun input(void: Int, attr: Attr<InputHTMLAttributes<HTMLInputElement>>, noinline block: DataNodes? = null)
    inline fun ins(void: Int, attr: Attr<InsHTMLAttributes<HTMLModElement>>, noinline block: DataNodes? = null)
    inline fun kbd(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun keygen(void: Int, attr: Attr<KeygenHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun label(void: Int, attr: Attr<LabelHTMLAttributes<HTMLLabelElement>>, noinline block: DataNodes? = null)
    inline fun legend(void: Int, attr: Attr<HTMLAttributes<HTMLLegendElement>>, noinline block: DataNodes? = null)
    inline fun li(void: Int, attr: Attr<LiHTMLAttributes<HTMLLIElement>>, noinline block: DataNodes? = null)
    inline fun link(void: Int, attr: Attr<LinkHTMLAttributes<HTMLLinkElement>>, noinline block: DataNodes? = null)
    inline fun main(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun map(void: Int, attr: Attr<MapHTMLAttributes<HTMLMapElement>>, noinline block: DataNodes? = null)
    inline fun mark(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun menu(void: Int, attr: Attr<MenuHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun menuitem(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun meta(void: Int, attr: Attr<MetaHTMLAttributes<HTMLMetaElement>>, noinline block: DataNodes? = null)
    inline fun meter(void: Int, attr: Attr<MeterHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun nav(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun noscript(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun objectElement(void: Int, attr: Attr<ObjectHTMLAttributes<HTMLObjectElement>>, noinline block: DataNodes? = null)
    inline fun ol(void: Int, attr: Attr<OlHTMLAttributes<HTMLOListElement>>, noinline block: DataNodes? = null)
    inline fun optgroup(void: Int, attr: Attr<OptgroupHTMLAttributes<HTMLOptGroupElement>>, noinline block: DataNodes? = null)
    inline fun option(void: Int, attr: Attr<OptionHTMLAttributes<HTMLOptionElement>>, noinline block: DataNodes? = null)
    inline fun output(void: Int, attr: Attr<OutputHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun p(void: Int, attr: Attr<HTMLAttributes<HTMLParagraphElement>>, noinline block: DataNodes? = null)
    inline fun param(void: Int, attr: Attr<ParamHTMLAttributes<HTMLParamElement>>, noinline block: DataNodes? = null)
    inline fun picture(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun pre(void: Int, attr: Attr<HTMLAttributes<HTMLPreElement>>, noinline block: DataNodes? = null)
    inline fun progress(void: Int, attr: Attr<ProgressHTMLAttributes<HTMLProgressElement>>, noinline block: DataNodes? = null)
    inline fun q(void: Int, attr: Attr<QuoteHTMLAttributes<HTMLQuoteElement>>, noinline block: DataNodes? = null)
    inline fun rp(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun rt(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun ruby(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun s(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun samp(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun script(void: Int, attr: Attr<ScriptHTMLAttributes<HTMLScriptElement>>, noinline block: DataNodes? = null)
    inline fun section(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun select(void: Int, attr: Attr<SelectHTMLAttributes<HTMLSelectElement>>, noinline block: DataNodes? = null)
    inline fun small(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun source(void: Int, attr: Attr<SourceHTMLAttributes<HTMLSourceElement>>, noinline block: DataNodes? = null)
    inline fun span(void: Int, attr: Attr<HTMLAttributes<HTMLSpanElement>>, noinline block: DataNodes? = null)
    inline fun strong(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun styleElement(void: Int, attr: Attr<StyleHTMLAttributes<HTMLStyleElement>>, noinline block: DataNodes? = null)
    inline fun sub(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun summary(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun sup(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun table(void: Int, attr: Attr<TableHTMLAttributes<HTMLTableElement>>, noinline block: DataNodes? = null)
    inline fun tbody(void: Int, attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, noinline block: DataNodes? = null)
    inline fun td(void: Int, attr: Attr<TdHTMLAttributes<HTMLTableCellElement>>, noinline block: DataNodes? = null)
    inline fun textarea(void: Int, attr: Attr<TextareaHTMLAttributes<HTMLTextAreaElement>>, noinline block: DataNodes? = null)
    inline fun tfoot(void: Int, attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, noinline block: DataNodes? = null)
    inline fun th(void: Int, attr: Attr<ThHTMLAttributes<HTMLTableCellElement>>, noinline block: DataNodes? = null)
    inline fun thead(void: Int, attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, noinline block: DataNodes? = null)
    inline fun time(void: Int, attr: Attr<TimeHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun title(void: Int, attr: Attr<HTMLAttributes<HTMLTitleElement>>, noinline block: DataNodes? = null)
    inline fun tr(void: Int, attr: Attr<HTMLAttributes<HTMLTableRowElement>>, noinline block: DataNodes? = null)
    inline fun track(void: Int, attr: Attr<TrackHTMLAttributes<HTMLTrackElement>>, noinline block: DataNodes? = null)
    inline fun u(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun ul(void: Int, attr: Attr<HTMLAttributes<HTMLUListElement>>, noinline block: DataNodes? = null)
    inline fun varElement(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun video(void: Int, attr: Attr<VideoHTMLAttributes<HTMLVideoElement>>, noinline block: DataNodes? = null)
    inline fun wbr(void: Int, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)

    inline fun a(void: Int, className: String, attr: Attr<AnchorHTMLAttributes<HTMLAnchorElement>>, noinline block: DataNodes? = null)
    inline fun address(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun area(void: Int, className: String, attr: Attr<AreaHTMLAttributes<HTMLAreaElement>>, noinline block: DataNodes? = null)
    inline fun article(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun aside(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun audio(void: Int, className: String, attr: Attr<AudioHTMLAttributes<HTMLAudioElement>>, noinline block: DataNodes? = null)
    inline fun b(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun base(void: Int, className: String, attr: Attr<BaseHTMLAttributes<HTMLBaseElement>>, noinline block: DataNodes? = null)
    inline fun bdi(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun bdo(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun big(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun blockquote(void: Int, className: String, attr: Attr<BlockquoteHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun body(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLBodyElement>>, noinline block: DataNodes? = null)
    inline fun br(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLBRElement>>, noinline block: DataNodes? = null)
    inline fun button(void: Int, className: String, attr: Attr<ButtonHTMLAttributes<HTMLButtonElement>>, noinline block: DataNodes? = null)
    inline fun canvas(void: Int, className: String, attr: Attr<CanvasHTMLAttributes<HTMLCanvasElement>>, noinline block: DataNodes? = null)
    inline fun caption(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun cite(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun code(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun col(void: Int, className: String, attr: Attr<ColHTMLAttributes<HTMLTableColElement>>, noinline block: DataNodes? = null)
    inline fun colgroup(void: Int, className: String, attr: Attr<ColgroupHTMLAttributes<HTMLTableColElement>>, noinline block: DataNodes? = null)
    inline fun data(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun datalist(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLDataListElement>>, noinline block: DataNodes? = null)
    inline fun dd(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun del(void: Int, className: String, attr: Attr<DelHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun details(void: Int, className: String, attr: Attr<DetailsHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun dfn(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun dialog(void: Int, className: String, attr: Attr<DialogHTMLAttributes<HTMLDialogElement>>, noinline block: DataNodes? = null)
    inline fun div(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLDivElement>>, noinline block: DataNodes? = null)
    inline fun dl(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLDListElement>>, noinline block: DataNodes? = null)
    inline fun dt(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun em(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun embed(void: Int, className: String, attr: Attr<EmbedHTMLAttributes<HTMLEmbedElement>>, noinline block: DataNodes? = null)
    inline fun fieldset(void: Int, className: String, attr: Attr<FieldsetHTMLAttributes<HTMLFieldSetElement>>, noinline block: DataNodes? = null)
    inline fun figcaption(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun figure(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun footer(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun form(void: Int, className: String, attr: Attr<FormHTMLAttributes<HTMLFormElement>>, noinline block: DataNodes? = null)
    inline fun h1(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun h2(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun h3(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun h4(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun h5(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun h6(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, noinline block: DataNodes? = null)
    inline fun head(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun header(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun hgroup(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun hr(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLHRElement>>, noinline block: DataNodes? = null)
    inline fun html(void: Int, className: String, attr: Attr<HtmlHTMLAttributes<HTMLHtmlElement>>, noinline block: DataNodes? = null)
    inline fun i(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun iframe(void: Int, className: String, attr: Attr<IframeHTMLAttributes<HTMLIFrameElement>>, noinline block: DataNodes? = null)
    inline fun img(void: Int, className: String, attr: Attr<ImgHTMLAttributes<HTMLImageElement>>, noinline block: DataNodes? = null)
    inline fun input(void: Int, className: String, attr: Attr<InputHTMLAttributes<HTMLInputElement>>, noinline block: DataNodes? = null)
    inline fun ins(void: Int, className: String, attr: Attr<InsHTMLAttributes<HTMLModElement>>, noinline block: DataNodes? = null)
    inline fun kbd(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun keygen(void: Int, className: String, attr: Attr<KeygenHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun label(void: Int, className: String, attr: Attr<LabelHTMLAttributes<HTMLLabelElement>>, noinline block: DataNodes? = null)
    inline fun legend(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLLegendElement>>, noinline block: DataNodes? = null)
    inline fun li(void: Int, className: String, attr: Attr<LiHTMLAttributes<HTMLLIElement>>, noinline block: DataNodes? = null)
    inline fun link(void: Int, className: String, attr: Attr<LinkHTMLAttributes<HTMLLinkElement>>, noinline block: DataNodes? = null)
    inline fun main(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun map(void: Int, className: String, attr: Attr<MapHTMLAttributes<HTMLMapElement>>, noinline block: DataNodes? = null)
    inline fun mark(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun menu(void: Int, className: String, attr: Attr<MenuHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun menuitem(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun meta(void: Int, className: String, attr: Attr<MetaHTMLAttributes<HTMLMetaElement>>, noinline block: DataNodes? = null)
    inline fun meter(void: Int, className: String, attr: Attr<MeterHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun nav(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun noscript(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun objectElement(void: Int, className: String, attr: Attr<ObjectHTMLAttributes<HTMLObjectElement>>, noinline block: DataNodes? = null)
    inline fun ol(void: Int, className: String, attr: Attr<OlHTMLAttributes<HTMLOListElement>>, noinline block: DataNodes? = null)
    inline fun optgroup(void: Int, className: String, attr: Attr<OptgroupHTMLAttributes<HTMLOptGroupElement>>, noinline block: DataNodes? = null)
    inline fun option(void: Int, className: String, attr: Attr<OptionHTMLAttributes<HTMLOptionElement>>, noinline block: DataNodes? = null)
    inline fun output(void: Int, className: String, attr: Attr<OutputHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun p(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLParagraphElement>>, noinline block: DataNodes? = null)
    inline fun param(void: Int, className: String, attr: Attr<ParamHTMLAttributes<HTMLParamElement>>, noinline block: DataNodes? = null)
    inline fun picture(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun pre(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLPreElement>>, noinline block: DataNodes? = null)
    inline fun progress(void: Int, className: String, attr: Attr<ProgressHTMLAttributes<HTMLProgressElement>>, noinline block: DataNodes? = null)
    inline fun q(void: Int, className: String, attr: Attr<QuoteHTMLAttributes<HTMLQuoteElement>>, noinline block: DataNodes? = null)
    inline fun rp(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun rt(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun ruby(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun s(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun samp(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun script(void: Int, className: String, attr: Attr<ScriptHTMLAttributes<HTMLScriptElement>>, noinline block: DataNodes? = null)
    inline fun section(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun select(void: Int, className: String, attr: Attr<SelectHTMLAttributes<HTMLSelectElement>>, noinline block: DataNodes? = null)
    inline fun small(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun source(void: Int, className: String, attr: Attr<SourceHTMLAttributes<HTMLSourceElement>>, noinline block: DataNodes? = null)
    inline fun span(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLSpanElement>>, noinline block: DataNodes? = null)
    inline fun strong(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun styleElement(void: Int, className: String, attr: Attr<StyleHTMLAttributes<HTMLStyleElement>>, noinline block: DataNodes? = null)
    inline fun sub(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun summary(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun sup(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun table(void: Int, className: String, attr: Attr<TableHTMLAttributes<HTMLTableElement>>, noinline block: DataNodes? = null)
    inline fun tbody(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, noinline block: DataNodes? = null)
    inline fun td(void: Int, className: String, attr: Attr<TdHTMLAttributes<HTMLTableCellElement>>, noinline block: DataNodes? = null)
    inline fun textarea(void: Int, className: String, attr: Attr<TextareaHTMLAttributes<HTMLTextAreaElement>>, noinline block: DataNodes? = null)
    inline fun tfoot(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, noinline block: DataNodes? = null)
    inline fun th(void: Int, className: String, attr: Attr<ThHTMLAttributes<HTMLTableCellElement>>, noinline block: DataNodes? = null)
    inline fun thead(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, noinline block: DataNodes? = null)
    inline fun time(void: Int, className: String, attr: Attr<TimeHTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun title(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLTitleElement>>, noinline block: DataNodes? = null)
    inline fun tr(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLTableRowElement>>, noinline block: DataNodes? = null)
    inline fun track(void: Int, className: String, attr: Attr<TrackHTMLAttributes<HTMLTrackElement>>, noinline block: DataNodes? = null)
    inline fun u(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun ul(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLUListElement>>, noinline block: DataNodes? = null)
    inline fun varElement(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)
    inline fun video(void: Int, className: String, attr: Attr<VideoHTMLAttributes<HTMLVideoElement>>, noinline block: DataNodes? = null)
    inline fun wbr(void: Int, className: String, attr: Attr<HTMLAttributes<HTMLElement>>, noinline block: DataNodes? = null)

    inline fun a(className: String? = null, block: Nodes)
    inline fun address(className: String? = null, block: Nodes)
    inline fun area(className: String? = null, block: Nodes)
    inline fun article(className: String? = null, block: Nodes)
    inline fun aside(className: String? = null, block: Nodes)
    inline fun audio(className: String? = null, block: Nodes)
    inline fun b(className: String? = null, block: Nodes)
    inline fun base(className: String? = null, block: Nodes)
    inline fun bdi(className: String? = null, block: Nodes)
    inline fun bdo(className: String? = null, block: Nodes)
    inline fun big(className: String? = null, block: Nodes)
    inline fun blockquote(className: String? = null, block: Nodes)
    inline fun body(className: String? = null, block: Nodes)
    inline fun br(className: String? = null, block: Nodes)
    inline fun button(className: String? = null, block: Nodes)
    inline fun canvas(className: String? = null, block: Nodes)
    inline fun caption(className: String? = null, block: Nodes)
    inline fun cite(className: String? = null, block: Nodes)
    inline fun code(className: String? = null, block: Nodes)
    inline fun col(className: String? = null, block: Nodes)
    inline fun colgroup(className: String? = null, block: Nodes)
    inline fun data(className: String? = null, block: Nodes)
    inline fun datalist(className: String? = null, block: Nodes)
    inline fun dd(className: String? = null, block: Nodes)
    inline fun del(className: String? = null, block: Nodes)
    inline fun details(className: String? = null, block: Nodes)
    inline fun dfn(className: String? = null, block: Nodes)
    inline fun dialog(className: String? = null, block: Nodes)
    inline fun div(className: String? = null, block: Nodes)
    inline fun dl(className: String? = null, block: Nodes)
    inline fun dt(className: String? = null, block: Nodes)
    inline fun em(className: String? = null, block: Nodes)
    inline fun embed(className: String? = null, block: Nodes)
    inline fun fieldset(className: String? = null, block: Nodes)
    inline fun figcaption(className: String? = null, block: Nodes)
    inline fun figure(className: String? = null, block: Nodes)
    inline fun footer(className: String? = null, block: Nodes)
    inline fun form(className: String? = null, block: Nodes)
    inline fun h1(className: String? = null, block: Nodes)
    inline fun h2(className: String? = null, block: Nodes)
    inline fun h3(className: String? = null, block: Nodes)
    inline fun h4(className: String? = null, block: Nodes)
    inline fun h5(className: String? = null, block: Nodes)
    inline fun h6(className: String? = null, block: Nodes)
    inline fun head(className: String? = null, block: Nodes)
    inline fun header(className: String? = null, block: Nodes)
    inline fun hgroup(className: String? = null, block: Nodes)
    inline fun hr(className: String? = null, block: Nodes)
    inline fun html(className: String? = null, block: Nodes)
    inline fun i(className: String? = null, block: Nodes)
    inline fun iframe(className: String? = null, block: Nodes)
    inline fun img(className: String? = null, block: Nodes)
    inline fun input(className: String? = null, block: Nodes)
    inline fun ins(className: String? = null, block: Nodes)
    inline fun kbd(className: String? = null, block: Nodes)
    inline fun keygen(className: String? = null, block: Nodes)
    inline fun label(className: String? = null, block: Nodes)
    inline fun legend(className: String? = null, block: Nodes)
    inline fun li(className: String? = null, block: Nodes)
    inline fun link(className: String? = null, block: Nodes)
    inline fun main(className: String? = null, block: Nodes)
    inline fun map(className: String? = null, block: Nodes)
    inline fun mark(className: String? = null, block: Nodes)
    inline fun menu(className: String? = null, block: Nodes)
    inline fun menuitem(className: String? = null, block: Nodes)
    inline fun meta(className: String? = null, block: Nodes)
    inline fun meter(className: String? = null, block: Nodes)
    inline fun nav(className: String? = null, block: Nodes)
    inline fun noscript(className: String? = null, block: Nodes)
    inline fun objectElement(className: String? = null, block: Nodes)
    inline fun ol(className: String? = null, block: Nodes)
    inline fun optgroup(className: String? = null, block: Nodes)
    inline fun option(className: String? = null, block: Nodes)
    inline fun output(className: String? = null, block: Nodes)
    inline fun p(className: String? = null, block: Nodes)
    inline fun param(className: String? = null, block: Nodes)
    inline fun picture(className: String? = null, block: Nodes)
    inline fun pre(className: String? = null, block: Nodes)
    inline fun progress(className: String? = null, block: Nodes)
    inline fun q(className: String? = null, block: Nodes)
    inline fun rp(className: String? = null, block: Nodes)
    inline fun rt(className: String? = null, block: Nodes)
    inline fun ruby(className: String? = null, block: Nodes)
    inline fun s(className: String? = null, block: Nodes)
    inline fun samp(className: String? = null, block: Nodes)
    inline fun script(className: String? = null, block: Nodes)
    inline fun section(className: String? = null, block: Nodes)
    inline fun select(className: String? = null, block: Nodes)
    inline fun small(className: String? = null, block: Nodes)
    inline fun source(className: String? = null, block: Nodes)
    inline fun span(className: String? = null, block: Nodes)
    inline fun strong(className: String? = null, block: Nodes)
    inline fun styleElement(className: String? = null, block: Nodes)
    inline fun sub(className: String? = null, block: Nodes)
    inline fun summary(className: String? = null, block: Nodes)
    inline fun sup(className: String? = null, block: Nodes)
    inline fun table(className: String? = null, block: Nodes)
    inline fun tbody(className: String? = null, block: Nodes)
    inline fun td(className: String? = null, block: Nodes)
    inline fun textarea(className: String? = null, block: Nodes)
    inline fun tfoot(className: String? = null, block: Nodes)
    inline fun th(className: String? = null, block: Nodes)
    inline fun thead(className: String? = null, block: Nodes)
    inline fun time(className: String? = null, block: Nodes)
    inline fun title(className: String? = null, block: Nodes)
    inline fun tr(className: String? = null, block: Nodes)
    inline fun track(className: String? = null, block: Nodes)
    inline fun u(className: String? = null, block: Nodes)
    inline fun ul(className: String? = null, block: Nodes)
    inline fun varElement(className: String? = null, block: Nodes)
    inline fun video(className: String? = null, block: Nodes)
    inline fun wbr(className: String? = null, block: Nodes)

    inline fun a(attr: Attr<AnchorHTMLAttributes<HTMLAnchorElement>>, block: Nodes)
    inline fun address(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun area(attr: Attr<AreaHTMLAttributes<HTMLAreaElement>>, block: Nodes)
    inline fun article(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun aside(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun audio(attr: Attr<AudioHTMLAttributes<HTMLAudioElement>>, block: Nodes)
    inline fun b(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun base(attr: Attr<BaseHTMLAttributes<HTMLBaseElement>>, block: Nodes)
    inline fun bdi(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun bdo(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun big(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun blockquote(attr: Attr<BlockquoteHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun body(attr: Attr<HTMLAttributes<HTMLBodyElement>>, block: Nodes)
    inline fun br(attr: Attr<HTMLAttributes<HTMLBRElement>>, block: Nodes)
    inline fun button(attr: Attr<ButtonHTMLAttributes<HTMLButtonElement>>, block: Nodes)
    inline fun canvas(attr: Attr<CanvasHTMLAttributes<HTMLCanvasElement>>, block: Nodes)
    inline fun caption(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun cite(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun code(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun col(attr: Attr<ColHTMLAttributes<HTMLTableColElement>>, block: Nodes)
    inline fun colgroup(attr: Attr<ColgroupHTMLAttributes<HTMLTableColElement>>, block: Nodes)
    inline fun data(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun datalist(attr: Attr<HTMLAttributes<HTMLDataListElement>>, block: Nodes)
    inline fun dd(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun del(attr: Attr<DelHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun details(attr: Attr<DetailsHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun dfn(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun dialog(attr: Attr<DialogHTMLAttributes<HTMLDialogElement>>, block: Nodes)
    inline fun div(attr: Attr<HTMLAttributes<HTMLDivElement>>, block: Nodes)
    inline fun dl(attr: Attr<HTMLAttributes<HTMLDListElement>>, block: Nodes)
    inline fun dt(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun em(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun embed(attr: Attr<EmbedHTMLAttributes<HTMLEmbedElement>>, block: Nodes)
    inline fun fieldset(attr: Attr<FieldsetHTMLAttributes<HTMLFieldSetElement>>, block: Nodes)
    inline fun figcaption(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun figure(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun footer(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun form(attr: Attr<FormHTMLAttributes<HTMLFormElement>>, block: Nodes)
    inline fun h1(attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun h2(attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun h3(attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun h4(attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun h5(attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun h6(attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun head(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun header(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun hgroup(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun hr(attr: Attr<HTMLAttributes<HTMLHRElement>>, block: Nodes)
    inline fun html(attr: Attr<HtmlHTMLAttributes<HTMLHtmlElement>>, block: Nodes)
    inline fun i(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun iframe(attr: Attr<IframeHTMLAttributes<HTMLIFrameElement>>, block: Nodes)
    inline fun img(attr: Attr<ImgHTMLAttributes<HTMLImageElement>>, block: Nodes)
    inline fun input(attr: Attr<InputHTMLAttributes<HTMLInputElement>>, block: Nodes)
    inline fun ins(attr: Attr<InsHTMLAttributes<HTMLModElement>>, block: Nodes)
    inline fun kbd(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun keygen(attr: Attr<KeygenHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun label(attr: Attr<LabelHTMLAttributes<HTMLLabelElement>>, block: Nodes)
    inline fun legend(attr: Attr<HTMLAttributes<HTMLLegendElement>>, block: Nodes)
    inline fun li(attr: Attr<LiHTMLAttributes<HTMLLIElement>>, block: Nodes)
    inline fun link(attr: Attr<LinkHTMLAttributes<HTMLLinkElement>>, block: Nodes)
    inline fun main(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun map(attr: Attr<MapHTMLAttributes<HTMLMapElement>>, block: Nodes)
    inline fun mark(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun menu(attr: Attr<MenuHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun menuitem(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun meta(attr: Attr<MetaHTMLAttributes<HTMLMetaElement>>, block: Nodes)
    inline fun meter(attr: Attr<MeterHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun nav(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun noscript(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun objectElement(attr: Attr<ObjectHTMLAttributes<HTMLObjectElement>>, block: Nodes)
    inline fun ol(attr: Attr<OlHTMLAttributes<HTMLOListElement>>, block: Nodes)
    inline fun optgroup(attr: Attr<OptgroupHTMLAttributes<HTMLOptGroupElement>>, block: Nodes)
    inline fun option(attr: Attr<OptionHTMLAttributes<HTMLOptionElement>>, block: Nodes)
    inline fun output(attr: Attr<OutputHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun p(attr: Attr<HTMLAttributes<HTMLParagraphElement>>, block: Nodes)
    inline fun param(attr: Attr<ParamHTMLAttributes<HTMLParamElement>>, block: Nodes)
    inline fun picture(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun pre(attr: Attr<HTMLAttributes<HTMLPreElement>>, block: Nodes)
    inline fun progress(attr: Attr<ProgressHTMLAttributes<HTMLProgressElement>>, block: Nodes)
    inline fun q(attr: Attr<QuoteHTMLAttributes<HTMLQuoteElement>>, block: Nodes)
    inline fun rp(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun rt(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun ruby(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun s(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun samp(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun script(attr: Attr<ScriptHTMLAttributes<HTMLScriptElement>>, block: Nodes)
    inline fun section(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun select(attr: Attr<SelectHTMLAttributes<HTMLSelectElement>>, block: Nodes)
    inline fun small(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun source(attr: Attr<SourceHTMLAttributes<HTMLSourceElement>>, block: Nodes)
    inline fun span(attr: Attr<HTMLAttributes<HTMLSpanElement>>, block: Nodes)
    inline fun strong(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun styleElement(attr: Attr<StyleHTMLAttributes<HTMLStyleElement>>, block: Nodes)
    inline fun sub(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun summary(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun sup(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun table(attr: Attr<TableHTMLAttributes<HTMLTableElement>>, block: Nodes)
    inline fun tbody(attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, block: Nodes)
    inline fun td(attr: Attr<TdHTMLAttributes<HTMLTableCellElement>>, block: Nodes)
    inline fun textarea(attr: Attr<TextareaHTMLAttributes<HTMLTextAreaElement>>, block: Nodes)
    inline fun tfoot(attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, block: Nodes)
    inline fun th(attr: Attr<ThHTMLAttributes<HTMLTableCellElement>>, block: Nodes)
    inline fun thead(attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, block: Nodes)
    inline fun time(attr: Attr<TimeHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun title(attr: Attr<HTMLAttributes<HTMLTitleElement>>, block: Nodes)
    inline fun tr(attr: Attr<HTMLAttributes<HTMLTableRowElement>>, block: Nodes)
    inline fun track(attr: Attr<TrackHTMLAttributes<HTMLTrackElement>>, block: Nodes)
    inline fun u(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun ul(attr: Attr<HTMLAttributes<HTMLUListElement>>, block: Nodes)
    inline fun varElement(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun video(attr: Attr<VideoHTMLAttributes<HTMLVideoElement>>, block: Nodes)
    inline fun wbr(attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)

    inline fun a(className: String, attr: Attr<AnchorHTMLAttributes<HTMLAnchorElement>>, block: Nodes)
    inline fun address(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun area(className: String, attr: Attr<AreaHTMLAttributes<HTMLAreaElement>>, block: Nodes)
    inline fun article(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun aside(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun audio(className: String, attr: Attr<AudioHTMLAttributes<HTMLAudioElement>>, block: Nodes)
    inline fun b(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun base(className: String, attr: Attr<BaseHTMLAttributes<HTMLBaseElement>>, block: Nodes)
    inline fun bdi(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun bdo(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun big(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun blockquote(className: String, attr: Attr<BlockquoteHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun body(className: String, attr: Attr<HTMLAttributes<HTMLBodyElement>>, block: Nodes)
    inline fun br(className: String, attr: Attr<HTMLAttributes<HTMLBRElement>>, block: Nodes)
    inline fun button(className: String, attr: Attr<ButtonHTMLAttributes<HTMLButtonElement>>, block: Nodes)
    inline fun canvas(className: String, attr: Attr<CanvasHTMLAttributes<HTMLCanvasElement>>, block: Nodes)
    inline fun caption(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun cite(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun code(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun col(className: String, attr: Attr<ColHTMLAttributes<HTMLTableColElement>>, block: Nodes)
    inline fun colgroup(className: String, attr: Attr<ColgroupHTMLAttributes<HTMLTableColElement>>, block: Nodes)
    inline fun data(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun datalist(className: String, attr: Attr<HTMLAttributes<HTMLDataListElement>>, block: Nodes)
    inline fun dd(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun del(className: String, attr: Attr<DelHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun details(className: String, attr: Attr<DetailsHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun dfn(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun dialog(className: String, attr: Attr<DialogHTMLAttributes<HTMLDialogElement>>, block: Nodes)
    inline fun div(className: String, attr: Attr<HTMLAttributes<HTMLDivElement>>, block: Nodes)
    inline fun dl(className: String, attr: Attr<HTMLAttributes<HTMLDListElement>>, block: Nodes)
    inline fun dt(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun em(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun embed(className: String, attr: Attr<EmbedHTMLAttributes<HTMLEmbedElement>>, block: Nodes)
    inline fun fieldset(className: String, attr: Attr<FieldsetHTMLAttributes<HTMLFieldSetElement>>, block: Nodes)
    inline fun figcaption(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun figure(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun footer(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun form(className: String, attr: Attr<FormHTMLAttributes<HTMLFormElement>>, block: Nodes)
    inline fun h1(className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun h2(className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun h3(className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun h4(className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun h5(className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun h6(className: String, attr: Attr<HTMLAttributes<HTMLHeadingElement>>, block: Nodes)
    inline fun head(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun header(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun hgroup(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun hr(className: String, attr: Attr<HTMLAttributes<HTMLHRElement>>, block: Nodes)
    inline fun html(className: String, attr: Attr<HtmlHTMLAttributes<HTMLHtmlElement>>, block: Nodes)
    inline fun i(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun iframe(className: String, attr: Attr<IframeHTMLAttributes<HTMLIFrameElement>>, block: Nodes)
    inline fun img(className: String, attr: Attr<ImgHTMLAttributes<HTMLImageElement>>, block: Nodes)
    inline fun input(className: String, attr: Attr<InputHTMLAttributes<HTMLInputElement>>, block: Nodes)
    inline fun ins(className: String, attr: Attr<InsHTMLAttributes<HTMLModElement>>, block: Nodes)
    inline fun kbd(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun keygen(className: String, attr: Attr<KeygenHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun label(className: String, attr: Attr<LabelHTMLAttributes<HTMLLabelElement>>, block: Nodes)
    inline fun legend(className: String, attr: Attr<HTMLAttributes<HTMLLegendElement>>, block: Nodes)
    inline fun li(className: String, attr: Attr<LiHTMLAttributes<HTMLLIElement>>, block: Nodes)
    inline fun link(className: String, attr: Attr<LinkHTMLAttributes<HTMLLinkElement>>, block: Nodes)
    inline fun main(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun map(className: String, attr: Attr<MapHTMLAttributes<HTMLMapElement>>, block: Nodes)
    inline fun mark(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun menu(className: String, attr: Attr<MenuHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun menuitem(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun meta(className: String, attr: Attr<MetaHTMLAttributes<HTMLMetaElement>>, block: Nodes)
    inline fun meter(className: String, attr: Attr<MeterHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun nav(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun noscript(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun objectElement(className: String, attr: Attr<ObjectHTMLAttributes<HTMLObjectElement>>, block: Nodes)
    inline fun ol(className: String, attr: Attr<OlHTMLAttributes<HTMLOListElement>>, block: Nodes)
    inline fun optgroup(className: String, attr: Attr<OptgroupHTMLAttributes<HTMLOptGroupElement>>, block: Nodes)
    inline fun option(className: String, attr: Attr<OptionHTMLAttributes<HTMLOptionElement>>, block: Nodes)
    inline fun output(className: String, attr: Attr<OutputHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun p(className: String, attr: Attr<HTMLAttributes<HTMLParagraphElement>>, block: Nodes)
    inline fun param(className: String, attr: Attr<ParamHTMLAttributes<HTMLParamElement>>, block: Nodes)
    inline fun picture(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun pre(className: String, attr: Attr<HTMLAttributes<HTMLPreElement>>, block: Nodes)
    inline fun progress(className: String, attr: Attr<ProgressHTMLAttributes<HTMLProgressElement>>, block: Nodes)
    inline fun q(className: String, attr: Attr<QuoteHTMLAttributes<HTMLQuoteElement>>, block: Nodes)
    inline fun rp(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun rt(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun ruby(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun s(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun samp(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun script(className: String, attr: Attr<ScriptHTMLAttributes<HTMLScriptElement>>, block: Nodes)
    inline fun section(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun select(className: String, attr: Attr<SelectHTMLAttributes<HTMLSelectElement>>, block: Nodes)
    inline fun small(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun source(className: String, attr: Attr<SourceHTMLAttributes<HTMLSourceElement>>, block: Nodes)
    inline fun span(className: String, attr: Attr<HTMLAttributes<HTMLSpanElement>>, block: Nodes)
    inline fun strong(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun styleElement(className: String, attr: Attr<StyleHTMLAttributes<HTMLStyleElement>>, block: Nodes)
    inline fun sub(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun summary(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun sup(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun table(className: String, attr: Attr<TableHTMLAttributes<HTMLTableElement>>, block: Nodes)
    inline fun tbody(className: String, attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, block: Nodes)
    inline fun td(className: String, attr: Attr<TdHTMLAttributes<HTMLTableCellElement>>, block: Nodes)
    inline fun textarea(className: String, attr: Attr<TextareaHTMLAttributes<HTMLTextAreaElement>>, block: Nodes)
    inline fun tfoot(className: String, attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, block: Nodes)
    inline fun th(className: String, attr: Attr<ThHTMLAttributes<HTMLTableCellElement>>, block: Nodes)
    inline fun thead(className: String, attr: Attr<HTMLAttributes<HTMLTableSectionElement>>, block: Nodes)
    inline fun time(className: String, attr: Attr<TimeHTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun title(className: String, attr: Attr<HTMLAttributes<HTMLTitleElement>>, block: Nodes)
    inline fun tr(className: String, attr: Attr<HTMLAttributes<HTMLTableRowElement>>, block: Nodes)
    inline fun track(className: String, attr: Attr<TrackHTMLAttributes<HTMLTrackElement>>, block: Nodes)
    inline fun u(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun ul(className: String, attr: Attr<HTMLAttributes<HTMLUListElement>>, block: Nodes)
    inline fun varElement(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)
    inline fun video(className: String, attr: Attr<VideoHTMLAttributes<HTMLVideoElement>>, block: Nodes)
    inline fun wbr(className: String, attr: Attr<HTMLAttributes<HTMLElement>>, block: Nodes)

    inline fun a(className: String? = null)
    inline fun address(className: String? = null)
    inline fun area(className: String? = null)
    inline fun article(className: String? = null)
    inline fun aside(className: String? = null)
    inline fun audio(className: String? = null)
    inline fun b(className: String? = null)
    inline fun base(className: String? = null)
    inline fun bdi(className: String? = null)
    inline fun bdo(className: String? = null)
    inline fun big(className: String? = null)
    inline fun blockquote(className: String? = null)
    inline fun body(className: String? = null)
    inline fun br(className: String? = null)
    inline fun button(className: String? = null)
    inline fun canvas(className: String? = null)
    inline fun caption(className: String? = null)
    inline fun cite(className: String? = null)
    inline fun code(className: String? = null)
    inline fun col(className: String? = null)
    inline fun colgroup(className: String? = null)
    inline fun data(className: String? = null)
    inline fun datalist(className: String? = null)
    inline fun dd(className: String? = null)
    inline fun del(className: String? = null)
    inline fun details(className: String? = null)
    inline fun dfn(className: String? = null)
    inline fun dialog(className: String? = null)
    inline fun div(className: String? = null)
    inline fun dl(className: String? = null)
    inline fun dt(className: String? = null)
    inline fun em(className: String? = null)
    inline fun embed(className: String? = null)
    inline fun fieldset(className: String? = null)
    inline fun figcaption(className: String? = null)
    inline fun figure(className: String? = null)
    inline fun footer(className: String? = null)
    inline fun form(className: String? = null)
    inline fun h1(className: String? = null)
    inline fun h2(className: String? = null)
    inline fun h3(className: String? = null)
    inline fun h4(className: String? = null)
    inline fun h5(className: String? = null)
    inline fun h6(className: String? = null)
    inline fun head(className: String? = null)
    inline fun header(className: String? = null)
    inline fun hgroup(className: String? = null)
    inline fun hr(className: String? = null)
    inline fun html(className: String? = null)
    inline fun i(className: String? = null)
    inline fun iframe(className: String? = null)
    inline fun img(className: String? = null)
    inline fun input(className: String? = null)
    inline fun ins(className: String? = null)
    inline fun kbd(className: String? = null)
    inline fun keygen(className: String? = null)
    inline fun label(className: String? = null)
    inline fun legend(className: String? = null)
    inline fun li(className: String? = null)
    inline fun link(className: String? = null)
    inline fun main(className: String? = null)
    inline fun map(className: String? = null)
    inline fun mark(className: String? = null)
    inline fun menu(className: String? = null)
    inline fun menuitem(className: String? = null)
    inline fun meta(className: String? = null)
    inline fun meter(className: String? = null)
    inline fun nav(className: String? = null)
    inline fun noscript(className: String? = null)
    inline fun objectElement(className: String? = null)
    inline fun ol(className: String? = null)
    inline fun optgroup(className: String? = null)
    inline fun option(className: String? = null)
    inline fun output(className: String? = null)
    inline fun p(className: String? = null)
    inline fun param(className: String? = null)
    inline fun picture(className: String? = null)
    inline fun pre(className: String? = null)
    inline fun progress(className: String? = null)
    inline fun q(className: String? = null)
    inline fun rp(className: String? = null)
    inline fun rt(className: String? = null)
    inline fun ruby(className: String? = null)
    inline fun s(className: String? = null)
    inline fun samp(className: String? = null)
    inline fun script(className: String? = null)
    inline fun section(className: String? = null)
    inline fun select(className: String? = null)
    inline fun small(className: String? = null)
    inline fun source(className: String? = null)
    inline fun span(className: String? = null)
    inline fun strong(className: String? = null)
    inline fun styleElement(className: String? = null)
    inline fun sub(className: String? = null)
    inline fun summary(className: String? = null)
    inline fun sup(className: String? = null)
    inline fun table(className: String? = null)
    inline fun tbody(className: String? = null)
    inline fun td(className: String? = null)
    inline fun textarea(className: String? = null)
    inline fun tfoot(className: String? = null)
    inline fun th(className: String? = null)
    inline fun thead(className: String? = null)
    inline fun time(className: String? = null)
    inline fun title(className: String? = null)
    inline fun tr(className: String? = null)
    inline fun track(className: String? = null)
    inline fun u(className: String? = null)
    inline fun ul(className: String? = null)
    inline fun varElement(className: String? = null)
    inline fun video(className: String? = null)
    inline fun wbr(className: String? = null)
}
