@file:Suppress("NOTHING_TO_INLINE", "DEPRECATION")

package cn.apisium.sarla.nodes

import cn.apisium.sarla.*
import cn.apisium.sarla.dom.*

@SarlaDsl
expect open class DataNodeBlock: NodeBlock {
    operator fun <T: Any> Data<T>.get(key: Any): Data<T>
    operator fun <T: Any> Data<T>.invoke(): T

    //inline operator fun Data<*>.get(key: Any): Data<*>
    //inline operator fun Data<*>.invoke(): Any
    inline operator fun <T: Number> Data<T>.plus(value: T): T

    inline operator fun <T: Number> Data<T>.unaryPlus()
}

@SarlaDsl
expect class E<A: HTMLAttributes<Q>, Q: Element>: NodeBlock {
    inline fun attributes(block: A.() -> Unit)
    inline fun styles(block: CSSProperties.() -> Unit)
    inline fun props(block: Props.() -> Unit)
    inline fun events(block: DOMEvents<Q>.() -> Unit)
}
@SarlaDsl
expect class D<A: HTMLAttributes<Q>, Q: Element>: DataNodeBlock {
    inline fun attributes(block: A.() -> Unit)
    inline fun styles(block: CSSProperties.() -> Unit)
    inline fun props(block: Props.() -> Unit)
    inline fun events(block: DOMEvents<Q>.() -> Unit)
}

@SarlaDsl
expect open class NodeBlock {
    inline operator fun String.unaryPlus()

    inline operator fun Number.unaryPlus()

    inline operator fun Nothing.unaryPlus()

    inline operator fun Unit.unaryPlus()

    inline operator fun <P, T: SarlaProp<P>> SarlaInstant<T>.invoke(props: P? = null, noinline block: Nodes? = null)
    inline operator fun <T: Sarla> SarlaInstant<T>.invoke(noinline block: Nodes? = null)
    inline operator fun <P, T: SarlaProp<P>> SarlaInstant<T>.invoke(void: Int, props: P? = null, noinline block: DataNodes? = null)
    inline operator fun <T: Sarla> SarlaInstant<T>.invoke(void: Int, noinline block: DataNodes? = null)

    inline operator fun <P, T: SarlaProp<P>> SarlaInlineInstant<T>.invoke(props: P? = null, noinline block: Nodes? = null)
    inline operator fun <T: Sarla> SarlaInlineInstant<T>.invoke(noinline block: Nodes? = null)
    inline operator fun <P, T: SarlaProp<P>> SarlaInlineInstant<T>.invoke(void: Int, props: P? = null, noinline block: DataNodes? = null)
    inline operator fun <T: Sarla> SarlaInlineInstant<T>.invoke(void: Int, noinline block: DataNodes? = null)

    inline fun tag(void: Int, name: String, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun tag(name: String, className: String? = null, block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun tag(name: String, className: String? = null)

    inline fun a(void: Int, className: String? = null, noinline block: D<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>.() -> Unit)
    inline fun address(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun area(void: Int, className: String? = null, noinline block: D<AreaHTMLAttributes<HTMLAreaElement>, HTMLAreaElement>.() -> Unit)
    inline fun article(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun aside(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun audio(void: Int, className: String? = null, noinline block: D<AudioHTMLAttributes<HTMLAudioElement>, HTMLAudioElement>.() -> Unit)
    inline fun b(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun base(void: Int, className: String? = null, noinline block: D<BaseHTMLAttributes<HTMLBaseElement>, HTMLBaseElement>.() -> Unit)
    inline fun bdi(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun bdo(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun big(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun blockquote(void: Int, className: String? = null, noinline block: D<BlockquoteHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun body(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLBodyElement>, HTMLBodyElement>.() -> Unit)
    inline fun br(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLBRElement>, HTMLBRElement>.() -> Unit)
    inline fun button(void: Int, className: String? = null, noinline block: D<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>.() -> Unit)
    inline fun canvas(void: Int, className: String? = null, noinline block: D<CanvasHTMLAttributes<HTMLCanvasElement>, HTMLCanvasElement>.() -> Unit)
    inline fun caption(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun cite(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun code(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun col(void: Int, className: String? = null, noinline block: D<ColHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>.() -> Unit)
    inline fun colgroup(void: Int, className: String? = null, noinline block: D<ColgroupHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>.() -> Unit)
    inline fun data(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun datalist(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLDataListElement>, HTMLDataListElement>.() -> Unit)
    inline fun dd(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun del(void: Int, className: String? = null, noinline block: D<DelHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun details(void: Int, className: String? = null, noinline block: D<DetailsHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun dfn(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun dialog(void: Int, className: String? = null, noinline block: D<DialogHTMLAttributes<HTMLDialogElement>, HTMLDialogElement>.() -> Unit)
    inline fun div(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLDivElement>, HTMLDivElement>.() -> Unit)
    inline fun dl(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLDListElement>, HTMLDListElement>.() -> Unit)
    inline fun dt(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun em(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun embed(void: Int, className: String? = null, noinline block: D<EmbedHTMLAttributes<HTMLEmbedElement>, HTMLEmbedElement>.() -> Unit)
    inline fun fieldset(void: Int, className: String? = null, noinline block: D<FieldsetHTMLAttributes<HTMLFieldSetElement>, HTMLFieldSetElement>.() -> Unit)
    inline fun figcaption(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun figure(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun footer(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun form(void: Int, className: String? = null, noinline block: D<FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>.() -> Unit)
    inline fun h1(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun h2(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun h3(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun h4(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun h5(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun h6(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun head(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun header(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun hgroup(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun hr(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLHRElement>, HTMLHRElement>.() -> Unit)
    inline fun html(void: Int, className: String? = null, noinline block: D<HtmlHTMLAttributes<HTMLHtmlElement>, HTMLHtmlElement>.() -> Unit)
    inline fun i(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun iframe(void: Int, className: String? = null, noinline block: D<IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>.() -> Unit)
    inline fun img(void: Int, className: String? = null, noinline block: D<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>.() -> Unit)
    inline fun input(void: Int, className: String? = null, noinline block: D<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>.() -> Unit)
    inline fun ins(void: Int, className: String? = null, noinline block: D<InsHTMLAttributes<HTMLModElement>, HTMLModElement>.() -> Unit)
    inline fun kbd(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun keygen(void: Int, className: String? = null, noinline block: D<KeygenHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun label(void: Int, className: String? = null, noinline block: D<LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>.() -> Unit)
    inline fun legend(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLLegendElement>, HTMLLegendElement>.() -> Unit)
    inline fun li(void: Int, className: String? = null, noinline block: D<LiHTMLAttributes<HTMLLIElement>, HTMLLIElement>.() -> Unit)
    inline fun link(void: Int, className: String? = null, noinline block: D<LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>.() -> Unit)
    inline fun main(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun map(void: Int, className: String? = null, noinline block: D<MapHTMLAttributes<HTMLMapElement>, HTMLMapElement>.() -> Unit)
    inline fun mark(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun menu(void: Int, className: String? = null, noinline block: D<MenuHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun menuitem(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun meta(void: Int, className: String? = null, noinline block: D<MetaHTMLAttributes<HTMLMetaElement>, HTMLMetaElement>.() -> Unit)
    inline fun meter(void: Int, className: String? = null, noinline block: D<MeterHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun nav(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun noscript(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun objectElement(void: Int, className: String? = null, noinline block: D<ObjectHTMLAttributes<HTMLObjectElement>, HTMLObjectElement>.() -> Unit)
    inline fun ol(void: Int, className: String? = null, noinline block: D<OlHTMLAttributes<HTMLOListElement>, HTMLOListElement>.() -> Unit)
    inline fun optgroup(void: Int, className: String? = null, noinline block: D<OptgroupHTMLAttributes<HTMLOptGroupElement>, HTMLOptGroupElement>.() -> Unit)
    inline fun option(void: Int, className: String? = null, noinline block: D<OptionHTMLAttributes<HTMLOptionElement>, HTMLOptionElement>.() -> Unit)
    inline fun output(void: Int, className: String? = null, noinline block: D<OutputHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun p(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>.() -> Unit)
    inline fun param(void: Int, className: String? = null, noinline block: D<ParamHTMLAttributes<HTMLParamElement>, HTMLParamElement>.() -> Unit)
    inline fun picture(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun pre(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLPreElement>, HTMLPreElement>.() -> Unit)
    inline fun progress(void: Int, className: String? = null, noinline block: D<ProgressHTMLAttributes<HTMLProgressElement>, HTMLProgressElement>.() -> Unit)
    inline fun q(void: Int, className: String? = null, noinline block: D<QuoteHTMLAttributes<HTMLQuoteElement>, HTMLQuoteElement>.() -> Unit)
    inline fun rp(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun rt(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun ruby(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun s(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun samp(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun script(void: Int, className: String? = null, noinline block: D<ScriptHTMLAttributes<HTMLScriptElement>, HTMLScriptElement>.() -> Unit)
    inline fun section(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun select(void: Int, className: String? = null, noinline block: D<SelectHTMLAttributes<HTMLSelectElement>, HTMLSelectElement>.() -> Unit)
    inline fun small(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun source(void: Int, className: String? = null, noinline block: D<SourceHTMLAttributes<HTMLSourceElement>, HTMLSourceElement>.() -> Unit)
    inline fun span(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>.() -> Unit)
    inline fun strong(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun styleElement(void: Int, className: String? = null, noinline block: D<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>.() -> Unit)
    inline fun sub(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun summary(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun sup(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun table(void: Int, className: String? = null, noinline block: D<TableHTMLAttributes<HTMLTableElement>, HTMLTableElement>.() -> Unit)
    inline fun tbody(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>.() -> Unit)
    inline fun td(void: Int, className: String? = null, noinline block: D<TdHTMLAttributes<HTMLTableCellElement>, HTMLTableCellElement>.() -> Unit)
    inline fun textarea(void: Int, className: String? = null, noinline block: D<TextareaHTMLAttributes<HTMLTextAreaElement>, HTMLTextAreaElement>.() -> Unit)
    inline fun tfoot(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>.() -> Unit)
    inline fun th(void: Int, className: String? = null, noinline block: D<ThHTMLAttributes<HTMLTableCellElement>, HTMLTableCellElement>.() -> Unit)
    inline fun thead(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>.() -> Unit)
    inline fun time(void: Int, className: String? = null, noinline block: D<TimeHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun title(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLTitleElement>, HTMLTitleElement>.() -> Unit)
    inline fun tr(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLTableRowElement>, HTMLTableRowElement>.() -> Unit)
    inline fun track(void: Int, className: String? = null, noinline block: D<TrackHTMLAttributes<HTMLTrackElement>, HTMLTrackElement>.() -> Unit)
    inline fun u(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun ul(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLUListElement>, HTMLUListElement>.() -> Unit)
    inline fun varElement(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun video(void: Int, className: String? = null, noinline block: D<VideoHTMLAttributes<HTMLVideoElement>, HTMLVideoElement>.() -> Unit)
    inline fun wbr(void: Int, className: String? = null, noinline block: D<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)

    inline fun a(className: String? = null, noinline block: E<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>.() -> Unit)
    inline fun address(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun area(className: String? = null, noinline block: E<AreaHTMLAttributes<HTMLAreaElement>, HTMLAreaElement>.() -> Unit)
    inline fun article(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun aside(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun audio(className: String? = null, noinline block: E<AudioHTMLAttributes<HTMLAudioElement>, HTMLAudioElement>.() -> Unit)
    inline fun b(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun base(className: String? = null, noinline block: E<BaseHTMLAttributes<HTMLBaseElement>, HTMLBaseElement>.() -> Unit)
    inline fun bdi(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun bdo(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun big(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun blockquote(className: String? = null, noinline block: E<BlockquoteHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun body(className: String? = null, noinline block: E<HTMLAttributes<HTMLBodyElement>, HTMLBodyElement>.() -> Unit)
    inline fun br(className: String? = null, noinline block: E<HTMLAttributes<HTMLBRElement>, HTMLBRElement>.() -> Unit)
    inline fun button(className: String? = null, noinline block: E<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>.() -> Unit)
    inline fun canvas(className: String? = null, noinline block: E<CanvasHTMLAttributes<HTMLCanvasElement>, HTMLCanvasElement>.() -> Unit)
    inline fun caption(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun cite(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun code(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun col(className: String? = null, noinline block: E<ColHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>.() -> Unit)
    inline fun colgroup(className: String? = null, noinline block: E<ColgroupHTMLAttributes<HTMLTableColElement>, HTMLTableColElement>.() -> Unit)
    inline fun data(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun datalist(className: String? = null, noinline block: E<HTMLAttributes<HTMLDataListElement>, HTMLDataListElement>.() -> Unit)
    inline fun dd(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun del(className: String? = null, noinline block: E<DelHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun details(className: String? = null, noinline block: E<DetailsHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun dfn(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun dialog(className: String? = null, noinline block: E<DialogHTMLAttributes<HTMLDialogElement>, HTMLDialogElement>.() -> Unit)
    inline fun div(className: String? = null, noinline block: E<HTMLAttributes<HTMLDivElement>, HTMLDivElement>.() -> Unit)
    inline fun dl(className: String? = null, noinline block: E<HTMLAttributes<HTMLDListElement>, HTMLDListElement>.() -> Unit)
    inline fun dt(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun em(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun embed(className: String? = null, noinline block: E<EmbedHTMLAttributes<HTMLEmbedElement>, HTMLEmbedElement>.() -> Unit)
    inline fun fieldset(className: String? = null, noinline block: E<FieldsetHTMLAttributes<HTMLFieldSetElement>, HTMLFieldSetElement>.() -> Unit)
    inline fun figcaption(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun figure(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun footer(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun form(className: String? = null, noinline block: E<FormHTMLAttributes<HTMLFormElement>, HTMLFormElement>.() -> Unit)
    inline fun h1(className: String? = null, noinline block: E<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun h2(className: String? = null, noinline block: E<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun h3(className: String? = null, noinline block: E<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun h4(className: String? = null, noinline block: E<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun h5(className: String? = null, noinline block: E<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun h6(className: String? = null, noinline block: E<HTMLAttributes<HTMLHeadingElement>, HTMLHeadingElement>.() -> Unit)
    inline fun head(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun header(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun hgroup(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun hr(className: String? = null, noinline block: E<HTMLAttributes<HTMLHRElement>, HTMLHRElement>.() -> Unit)
    inline fun html(className: String? = null, noinline block: E<HtmlHTMLAttributes<HTMLHtmlElement>, HTMLHtmlElement>.() -> Unit)
    inline fun i(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun iframe(className: String? = null, noinline block: E<IframeHTMLAttributes<HTMLIFrameElement>, HTMLIFrameElement>.() -> Unit)
    inline fun img(className: String? = null, noinline block: E<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>.() -> Unit)
    inline fun input(className: String? = null, noinline block: E<InputHTMLAttributes<HTMLInputElement>, HTMLInputElement>.() -> Unit)
    inline fun ins(className: String? = null, noinline block: E<InsHTMLAttributes<HTMLModElement>, HTMLModElement>.() -> Unit)
    inline fun kbd(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun keygen(className: String? = null, noinline block: E<KeygenHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun label(className: String? = null, noinline block: E<LabelHTMLAttributes<HTMLLabelElement>, HTMLLabelElement>.() -> Unit)
    inline fun legend(className: String? = null, noinline block: E<HTMLAttributes<HTMLLegendElement>, HTMLLegendElement>.() -> Unit)
    inline fun li(className: String? = null, noinline block: E<LiHTMLAttributes<HTMLLIElement>, HTMLLIElement>.() -> Unit)
    inline fun link(className: String? = null, noinline block: E<LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>.() -> Unit)
    inline fun main(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun map(className: String? = null, noinline block: E<MapHTMLAttributes<HTMLMapElement>, HTMLMapElement>.() -> Unit)
    inline fun mark(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun menu(className: String? = null, noinline block: E<MenuHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun menuitem(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun meta(className: String? = null, noinline block: E<MetaHTMLAttributes<HTMLMetaElement>, HTMLMetaElement>.() -> Unit)
    inline fun meter(className: String? = null, noinline block: E<MeterHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun nav(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun noscript(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun objectElement(className: String? = null, noinline block: E<ObjectHTMLAttributes<HTMLObjectElement>, HTMLObjectElement>.() -> Unit)
    inline fun ol(className: String? = null, noinline block: E<OlHTMLAttributes<HTMLOListElement>, HTMLOListElement>.() -> Unit)
    inline fun optgroup(className: String? = null, noinline block: E<OptgroupHTMLAttributes<HTMLOptGroupElement>, HTMLOptGroupElement>.() -> Unit)
    inline fun option(className: String? = null, noinline block: E<OptionHTMLAttributes<HTMLOptionElement>, HTMLOptionElement>.() -> Unit)
    inline fun output(className: String? = null, noinline block: E<OutputHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun p(className: String? = null, noinline block: E<HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>.() -> Unit)
    inline fun param(className: String? = null, noinline block: E<ParamHTMLAttributes<HTMLParamElement>, HTMLParamElement>.() -> Unit)
    inline fun picture(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun pre(className: String? = null, noinline block: E<HTMLAttributes<HTMLPreElement>, HTMLPreElement>.() -> Unit)
    inline fun progress(className: String? = null, noinline block: E<ProgressHTMLAttributes<HTMLProgressElement>, HTMLProgressElement>.() -> Unit)
    inline fun q(className: String? = null, noinline block: E<QuoteHTMLAttributes<HTMLQuoteElement>, HTMLQuoteElement>.() -> Unit)
    inline fun rp(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun rt(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun ruby(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun s(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun samp(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun script(className: String? = null, noinline block: E<ScriptHTMLAttributes<HTMLScriptElement>, HTMLScriptElement>.() -> Unit)
    inline fun section(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun select(className: String? = null, noinline block: E<SelectHTMLAttributes<HTMLSelectElement>, HTMLSelectElement>.() -> Unit)
    inline fun small(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun source(className: String? = null, noinline block: E<SourceHTMLAttributes<HTMLSourceElement>, HTMLSourceElement>.() -> Unit)
    inline fun span(className: String? = null, noinline block: E<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>.() -> Unit)
    inline fun strong(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun styleElement(className: String? = null, noinline block: E<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>.() -> Unit)
    inline fun sub(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun summary(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun sup(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun table(className: String? = null, noinline block: E<TableHTMLAttributes<HTMLTableElement>, HTMLTableElement>.() -> Unit)
    inline fun tbody(className: String? = null, noinline block: E<HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>.() -> Unit)
    inline fun td(className: String? = null, noinline block: E<TdHTMLAttributes<HTMLTableCellElement>, HTMLTableCellElement>.() -> Unit)
    inline fun textarea(className: String? = null, noinline block: E<TextareaHTMLAttributes<HTMLTextAreaElement>, HTMLTextAreaElement>.() -> Unit)
    inline fun tfoot(className: String? = null, noinline block: E<HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>.() -> Unit)
    inline fun th(className: String? = null, noinline block: E<ThHTMLAttributes<HTMLTableCellElement>, HTMLTableCellElement>.() -> Unit)
    inline fun thead(className: String? = null, noinline block: E<HTMLAttributes<HTMLTableSectionElement>, HTMLTableSectionElement>.() -> Unit)
    inline fun time(className: String? = null, noinline block: E<TimeHTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun title(className: String? = null, noinline block: E<HTMLAttributes<HTMLTitleElement>, HTMLTitleElement>.() -> Unit)
    inline fun tr(className: String? = null, noinline block: E<HTMLAttributes<HTMLTableRowElement>, HTMLTableRowElement>.() -> Unit)
    inline fun track(className: String? = null, noinline block: E<TrackHTMLAttributes<HTMLTrackElement>, HTMLTrackElement>.() -> Unit)
    inline fun u(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun ul(className: String? = null, noinline block: E<HTMLAttributes<HTMLUListElement>, HTMLUListElement>.() -> Unit)
    inline fun varElement(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)
    inline fun video(className: String? = null, noinline block: E<VideoHTMLAttributes<HTMLVideoElement>, HTMLVideoElement>.() -> Unit)
    inline fun wbr(className: String? = null, noinline block: E<HTMLAttributes<HTMLElement>, HTMLElement>.() -> Unit)

    inline fun a(className: String? = null)
    inline fun address(className: String? = null)
    inline fun area(className: String? = null)
    inline fun article(className: String? = null)
    inline fun aside(className: String? = null)
    inline fun audio(className: String? = null)
    inline fun b(className: String? = null)
    inline fun base(className: String? = null)
    inline fun bdi(className: String? = null)
    inline fun bdo(className: String? = null)
    inline fun big(className: String? = null)
    inline fun blockquote(className: String? = null)
    inline fun body(className: String? = null)
    inline fun br(className: String? = null)
    inline fun button(className: String? = null)
    inline fun canvas(className: String? = null)
    inline fun caption(className: String? = null)
    inline fun cite(className: String? = null)
    inline fun code(className: String? = null)
    inline fun col(className: String? = null)
    inline fun colgroup(className: String? = null)
    inline fun data(className: String? = null)
    inline fun datalist(className: String? = null)
    inline fun dd(className: String? = null)
    inline fun del(className: String? = null)
    inline fun details(className: String? = null)
    inline fun dfn(className: String? = null)
    inline fun dialog(className: String? = null)
    inline fun div(className: String? = null)
    inline fun dl(className: String? = null)
    inline fun dt(className: String? = null)
    inline fun em(className: String? = null)
    inline fun embed(className: String? = null)
    inline fun fieldset(className: String? = null)
    inline fun figcaption(className: String? = null)
    inline fun figure(className: String? = null)
    inline fun footer(className: String? = null)
    inline fun form(className: String? = null)
    inline fun h1(className: String? = null)
    inline fun h2(className: String? = null)
    inline fun h3(className: String? = null)
    inline fun h4(className: String? = null)
    inline fun h5(className: String? = null)
    inline fun h6(className: String? = null)
    inline fun head(className: String? = null)
    inline fun header(className: String? = null)
    inline fun hgroup(className: String? = null)
    inline fun hr(className: String? = null)
    inline fun html(className: String? = null)
    inline fun i(className: String? = null)
    inline fun iframe(className: String? = null)
    inline fun img(className: String? = null)
    inline fun input(className: String? = null)
    inline fun ins(className: String? = null)
    inline fun kbd(className: String? = null)
    inline fun keygen(className: String? = null)
    inline fun label(className: String? = null)
    inline fun legend(className: String? = null)
    inline fun li(className: String? = null)
    inline fun link(className: String? = null)
    inline fun main(className: String? = null)
    inline fun map(className: String? = null)
    inline fun mark(className: String? = null)
    inline fun menu(className: String? = null)
    inline fun menuitem(className: String? = null)
    inline fun meta(className: String? = null)
    inline fun meter(className: String? = null)
    inline fun nav(className: String? = null)
    inline fun noscript(className: String? = null)
    inline fun objectElement(className: String? = null)
    inline fun ol(className: String? = null)
    inline fun optgroup(className: String? = null)
    inline fun option(className: String? = null)
    inline fun output(className: String? = null)
    inline fun p(className: String? = null)
    inline fun param(className: String? = null)
    inline fun picture(className: String? = null)
    inline fun pre(className: String? = null)
    inline fun progress(className: String? = null)
    inline fun q(className: String? = null)
    inline fun rp(className: String? = null)
    inline fun rt(className: String? = null)
    inline fun ruby(className: String? = null)
    inline fun s(className: String? = null)
    inline fun samp(className: String? = null)
    inline fun script(className: String? = null)
    inline fun section(className: String? = null)
    inline fun select(className: String? = null)
    inline fun small(className: String? = null)
    inline fun source(className: String? = null)
    inline fun span(className: String? = null)
    inline fun strong(className: String? = null)
    inline fun styleElement(className: String? = null)
    inline fun sub(className: String? = null)
    inline fun summary(className: String? = null)
    inline fun sup(className: String? = null)
    inline fun table(className: String? = null)
    inline fun tbody(className: String? = null)
    inline fun td(className: String? = null)
    inline fun textarea(className: String? = null)
    inline fun tfoot(className: String? = null)
    inline fun th(className: String? = null)
    inline fun thead(className: String? = null)
    inline fun time(className: String? = null)
    inline fun title(className: String? = null)
    inline fun tr(className: String? = null)
    inline fun track(className: String? = null)
    inline fun u(className: String? = null)
    inline fun ul(className: String? = null)
    inline fun varElement(className: String? = null)
    inline fun video(className: String? = null)
    inline fun wbr(className: String? = null)
}
