@file:Suppress("UNUSED")

package cn.apisium.sarla.dom

external interface CSSProperties {
    var alignContent: String?
    var alignItems: String?
    var alignSelf: String?
    var alignmentBaseline: String?
    var all: String?
    var animation: String?
    var animationDelay: String?
    var animationDirection: String?
    var animationDuration: String?
    var animationFillMode: String?
    var animationIterationCount: String?
    var animationName: String?
    var animationPlayState: String?
    var animationTimingFunction: String?
    var backfaceVisibility: String?
    var background: String?
    var backgroundAttachment: String?
    var backgroundBlendMode: String?
    var backgroundClip: String?
    var backgroundColor: String?
    var backgroundImage: String?
    var backgroundOrigin: String?
    var backgroundPosition: String?
    var backgroundPositionX: String?
    var backgroundPositionY: String?
    var backgroundRepeat: String?
    var backgroundRepeatX: String?
    var backgroundRepeatY: String?
    var backgroundSize: String?
    var baselineShift: String?
    var blockSize: String?
    var border: String?
    var borderBlockEnd: String?
    var borderBlockEndColor: String?
    var borderBlockEndStyle: String?
    var borderBlockEndWidth: String?
    var borderBlockStart: String?
    var borderBlockStartColor: String?
    var borderBlockStartStyle: String?
    var borderBlockStartWidth: String?
    var borderBottom: String?
    var borderBottomColor: String?
    var borderBottomLeftRadius: String?
    var borderBottomRightRadius: String?
    var borderBottomStyle: String?
    var borderBottomWidth: String?
    var borderCollapse: String?
    var borderColor: String?
    var borderImage: String?
    var borderImageOutset: String?
    var borderImageRepeat: String?
    var borderImageSlice: String?
    var borderImageSource: String?
    var borderImageWidth: String?
    var borderInlineEnd: String?
    var borderInlineEndColor: String?
    var borderInlineEndStyle: String?
    var borderInlineEndWidth: String?
    var borderInlineStart: String?
    var borderInlineStartColor: String?
    var borderInlineStartStyle: String?
    var borderInlineStartWidth: String?
    var borderLeft: String?
    var borderLeftColor: String?
    var borderLeftStyle: String?
    var borderLeftWidth: String?
    var borderRadius: String?
    var borderRight: String?
    var borderRightColor: String?
    var borderRightStyle: String?
    var borderRightWidth: String?
    var borderSpacing: String?
    var borderStyle: String?
    var borderTop: String?
    var borderTopColor: String?
    var borderTopLeftRadius: String?
    var borderTopRightRadius: String?
    var borderTopStyle: String?
    var borderTopWidth: String?
    var borderWidth: String?
    var bottom: String?
    var boxShadow: String?
    var boxSizing: String?
    var breakAfter: String?
    var breakBefore: String?
    var breakInside: String?
    var bufferedRendering: String?
    var captionSide: String?
    var caretColor: String?
    var clear: String?
    var clip: String?
    var clipPath: String?
    var clipRule: String?
    var color: String?
    var colorInterpolation: String?
    var colorInterpolationFilters: String?
    var colorRendering: String?
    var columnCount: String?
    var columnFill: String?
    var columnGap: String?
    var columnRule: String?
    var columnRuleColor: String?
    var columnRuleStyle: String?
    var columnRuleWidth: String?
    var columnSpan: String?
    var columnWidth: String?
    var columns: String?
    var contain: String?
    var content: String?
    var counterIncrement: String?
    var counterReset: String?
    var cursor: String?
    var cx: String?
    var cy: String?
    var d: String?
    var direction: String?
    var display: String?
    var dominantBaseline: String?
    var emptyCells: String?
    var fill: String?
    var fillOpacity: String?
    var fillRule: String?
    var filter: String?
    var flex: String?
    var flexBasis: String?
    var flexDirection: String?
    var flexFlow: String?
    var flexGrow: String?
    var flexShrink: String?
    var flexWrap: String?
    var float: String?
    var floodColor: String?
    var floodOpacity: String?
    var font: String?
    var fontDisplay: String?
    var fontFamily: String?
    var fontFeatureSettings: String?
    var fontKerning: String?
    var fontSize: String?
    var fontStretch: String?
    var fontStyle: String?
    var fontVariant: String?
    var fontVariantCaps: String?
    var fontVariantEastAsian: String?
    var fontVariantLigatures: String?
    var fontVariantNumeric: String?
    var fontVariationSettings: String?
    var fontWeight: String?
    var gap: String?
    var grid: String?
    var gridArea: String?
    var gridAutoColumns: String?
    var gridAutoFlow: String?
    var gridAutoRows: String?
    var gridColumn: String?
    var gridColumnEnd: String?
    var gridColumnGap: String?
    var gridColumnStart: String?
    var gridGap: String?
    var gridRow: String?
    var gridRowEnd: String?
    var gridRowGap: String?
    var gridRowStart: String?
    var gridTemplate: String?
    var gridTemplateAreas: String?
    var gridTemplateColumns: String?
    var gridTemplateRows: String?
    var height: String?
    var hyphens: String?
    var imageRendering: String?
    var inlineSize: String?
    var isolation: String?
    var justifyContent: String?
    var justifyItems: String?
    var justifySelf: String?
    var left: String?
    var letterSpacing: String?
    var lightingColor: String?
    var lineBreak: String?
    var lineHeight: String?
    var listStyle: String?
    var listStyleImage: String?
    var listStylePosition: String?
    var listStyleType: String?
    var margin: String?
    var marginBlockEnd: String?
    var marginBlockStart: String?
    var marginBottom: String?
    var marginInlineEnd: String?
    var marginInlineStart: String?
    var marginLeft: String?
    var marginRight: String?
    var marginTop: String?
    var marker: String?
    var markerEnd: String?
    var markerMid: String?
    var markerStart: String?
    var mask: String?
    var maskType: String?
    var maxBlockSize: String?
    var maxHeight: String?
    var maxInlineSize: String?
    var maxWidth: String?
    var maxZoom: String?
    var minBlockSize: String?
    var minHeight: String?
    var minInlineSize: String?
    var minWidth: String?
    var minZoom: String?
    var mixBlendMode: String?
    var objectFit: String?
    var objectPosition: String?
    var offset: String?
    var offsetDistance: String?
    var offsetPath: String?
    var offsetRotate: String?
    var opacity: String?
    var order: String?
    var orientation: String?
    var orphans: String?
    var outline: String?
    var outlineColor: String?
    var outlineOffset: String?
    var outlineStyle: String?
    var outlineWidth: String?
    var overflow: String?
    var overflowAnchor: String?
    var overflowWrap: String?
    var overflowX: String?
    var overflowY: String?
    var overscrollBehavior: String?
    var overscrollBehaviorX: String?
    var overscrollBehaviorY: String?
    var padding: String?
    var paddingBlockEnd: String?
    var paddingBlockStart: String?
    var paddingBottom: String?
    var paddingInlineEnd: String?
    var paddingInlineStart: String?
    var paddingLeft: String?
    var paddingRight: String?
    var paddingTop: String?
    var page: String?
    var pageBreakAfter: String?
    var pageBreakBefore: String?
    var pageBreakInside: String?
    var paintOrder: String?
    var perspective: String?
    var perspectiveOrigin: String?
    var placeContent: String?
    var placeItems: String?
    var placeSelf: String?
    var pointerEvents: String?
    var position: String?
    var quotes: String?
    var r: String?
    var resize: String?
    var right: String?
    var rowGap: String?
    var rx: String?
    var ry: String?
    var scrollBehavior: String?
    var scrollMargin: String?
    var scrollMarginBlock: String?
    var scrollMarginBlockEnd: String?
    var scrollMarginBlockStart: String?
    var scrollMarginBottom: String?
    var scrollMarginInline: String?
    var scrollMarginInlineEnd: String?
    var scrollMarginInlineStart: String?
    var scrollMarginLeft: String?
    var scrollMarginRight: String?
    var scrollMarginTop: String?
    var scrollPadding: String?
    var scrollPaddingBlock: String?
    var scrollPaddingBlockEnd: String?
    var scrollPaddingBlockStart: String?
    var scrollPaddingBottom: String?
    var scrollPaddingInline: String?
    var scrollPaddingInlineEnd: String?
    var scrollPaddingInlineStart: String?
    var scrollPaddingLeft: String?
    var scrollPaddingRight: String?
    var scrollPaddingTop: String?
    var scrollSnapAlign: String?
    var scrollSnapStop: String?
    var scrollSnapType: String?
    var shapeImageThreshold: String?
    var shapeMargin: String?
    var shapeOutside: String?
    var shapeRendering: String?
    var size: String?
    var speak: String?
    var src: String?
    var stopColor: String?
    var stopOpacity: String?
    var stroke: String?
    var strokeDasharray: String?
    var strokeDashoffset: String?
    var strokeLinecap: String?
    var strokeLinejoin: String?
    var strokeMiterlimit: String?
    var strokeOpacity: String?
    var strokeWidth: String?
    var tabSize: String?
    var tableLayout: String?
    var textAlign: String?
    var textAlignLast: String?
    var textAnchor: String?
    var textCombineUpright: String?
    var textDecoration: String?
    var textDecorationColor: String?
    var textDecorationLine: String?
    var textDecorationSkipInk: String?
    var textDecorationStyle: String?
    var textIndent: String?
    var textOrientation: String?
    var textOverflow: String?
    var textRendering: String?
    var textShadow: String?
    var textSizeAdjust: String?
    var textTransform: String?
    var textUnderlinePosition: String?
    var top: String?
    var touchAction: String?
    var transform: String?
    var transformBox: String?
    var transformOrigin: String?
    var transformStyle: String?
    var transition: String?
    var transitionDelay: String?
    var transitionDuration: String?
    var transitionProperty: String?
    var transitionTimingFunction: String?
    var unicodeBidi: String?
    var unicodeRange: String?
    var userSelect: String?
    var userZoom: String?
    var vectorEffect: String?
    var verticalAlign: String?
    var visibility: String?
    var webkitAlignContent: String?
    var webkitAlignItems: String?
    var webkitAlignSelf: String?
    var webkitAnimation: String?
    var webkitAnimationDelay: String?
    var webkitAnimationDirection: String?
    var webkitAnimationDuration: String?
    var webkitAnimationFillMode: String?
    var webkitAnimationIterationCount: String?
    var webkitAnimationName: String?
    var webkitAnimationPlayState: String?
    var webkitAnimationTimingFunction: String?
    var webkitAppRegion: String?
    var webkitAppearance: String?
    var webkitBackfaceVisibility: String?
    var webkitBackgroundClip: String?
    var webkitBackgroundOrigin: String?
    var webkitBackgroundSize: String?
    var webkitBorderAfter: String?
    var webkitBorderAfterColor: String?
    var webkitBorderAfterStyle: String?
    var webkitBorderAfterWidth: String?
    var webkitBorderBefore: String?
    var webkitBorderBeforeColor: String?
    var webkitBorderBeforeStyle: String?
    var webkitBorderBeforeWidth: String?
    var webkitBorderBottomLeftRadius: String?
    var webkitBorderBottomRightRadius: String?
    var webkitBorderEnd: String?
    var webkitBorderEndColor: String?
    var webkitBorderEndStyle: String?
    var webkitBorderEndWidth: String?
    var webkitBorderHorizontalSpacing: String?
    var webkitBorderImage: String?
    var webkitBorderRadius: String?
    var webkitBorderStart: String?
    var webkitBorderStartColor: String?
    var webkitBorderStartStyle: String?
    var webkitBorderStartWidth: String?
    var webkitBorderTopLeftRadius: String?
    var webkitBorderTopRightRadius: String?
    var webkitBorderVerticalSpacing: String?
    var webkitBoxAlign: String?
    var webkitBoxDecorationBreak: String?
    var webkitBoxDirection: String?
    var webkitBoxFlex: String?
    var webkitBoxOrdinalGroup: String?
    var webkitBoxOrient: String?
    var webkitBoxPack: String?
    var webkitBoxReflect: String?
    var webkitBoxShadow: String?
    var webkitBoxSizing: String?
    var webkitClipPath: String?
    var webkitColumnBreakAfter: String?
    var webkitColumnBreakBefore: String?
    var webkitColumnBreakInside: String?
    var webkitColumnCount: String?
    var webkitColumnGap: String?
    var webkitColumnRule: String?
    var webkitColumnRuleColor: String?
    var webkitColumnRuleStyle: String?
    var webkitColumnRuleWidth: String?
    var webkitColumnSpan: String?
    var webkitColumnWidth: String?
    var webkitColumns: String?
    var webkitFilter: String?
    var webkitFlex: String?
    var webkitFlexBasis: String?
    var webkitFlexDirection: String?
    var webkitFlexFlow: String?
    var webkitFlexGrow: String?
    var webkitFlexShrink: String?
    var webkitFlexWrap: String?
    var webkitFontFeatureSettings: String?
    var webkitFontSizeDelta: String?
    var webkitFontSmoothing: String?
    var webkitHighlight: String?
    var webkitHyphenateCharacter: String?
    var webkitJustifyContent: String?
    var webkitLineBreak: String?
    var webkitLineClamp: String?
    var webkitLocale: String?
    var webkitLogicalHeight: String?
    var webkitLogicalWidth: String?
    var webkitMarginAfter: String?
    var webkitMarginAfterCollapse: String?
    var webkitMarginBefore: String?
    var webkitMarginBeforeCollapse: String?
    var webkitMarginBottomCollapse: String?
    var webkitMarginCollapse: String?
    var webkitMarginEnd: String?
    var webkitMarginStart: String?
    var webkitMarginTopCollapse: String?
    var webkitMask: String?
    var webkitMaskBoxImage: String?
    var webkitMaskBoxImageOutset: String?
    var webkitMaskBoxImageRepeat: String?
    var webkitMaskBoxImageSlice: String?
    var webkitMaskBoxImageSource: String?
    var webkitMaskBoxImageWidth: String?
    var webkitMaskClip: String?
    var webkitMaskComposite: String?
    var webkitMaskImage: String?
    var webkitMaskOrigin: String?
    var webkitMaskPosition: String?
    var webkitMaskPositionX: String?
    var webkitMaskPositionY: String?
    var webkitMaskRepeat: String?
    var webkitMaskRepeatX: String?
    var webkitMaskRepeatY: String?
    var webkitMaskSize: String?
    var webkitMaxLogicalHeight: String?
    var webkitMaxLogicalWidth: String?
    var webkitMinLogicalHeight: String?
    var webkitMinLogicalWidth: String?
    var webkitOpacity: String?
    var webkitOrder: String?
    var webkitPaddingAfter: String?
    var webkitPaddingBefore: String?
    var webkitPaddingEnd: String?
    var webkitPaddingStart: String?
    var webkitPerspective: String?
    var webkitPerspectiveOrigin: String?
    var webkitPerspectiveOriginX: String?
    var webkitPerspectiveOriginY: String?
    var webkitPrintColorAdjust: String?
    var webkitRtlOrdering: String?
    var webkitRubyPosition: String?
    var webkitShapeImageThreshold: String?
    var webkitShapeMargin: String?
    var webkitShapeOutside: String?
    var webkitTapHighlightColor: String?
    var webkitTextCombine: String?
    var webkitTextDecorationsInEffect: String?
    var webkitTextEmphasis: String?
    var webkitTextEmphasisColor: String?
    var webkitTextEmphasisPosition: String?
    var webkitTextEmphasisStyle: String?
    var webkitTextFillColor: String?
    var webkitTextOrientation: String?
    var webkitTextSecurity: String?
    var webkitTextSizeAdjust: String?
    var webkitTextStroke: String?
    var webkitTextStrokeColor: String?
    var webkitTextStrokeWidth: String?
    var webkitTransform: String?
    var webkitTransformOrigin: String?
    var webkitTransformOriginX: String?
    var webkitTransformOriginY: String?
    var webkitTransformOriginZ: String?
    var webkitTransformStyle: String?
    var webkitTransition: String?
    var webkitTransitionDelay: String?
    var webkitTransitionDuration: String?
    var webkitTransitionProperty: String?
    var webkitTransitionTimingFunction: String?
    var webkitUserDrag: String?
    var webkitUserModify: String?
    var webkitUserSelect: String?
    var webkitWritingMode: String?
    var whiteSpace: String?
    var widows: String?
    var width: String?
    var willChange: String?
    var wordBreak: String?
    var wordSpacing: String?
    var wordWrap: String?
    var writingMode: String?
    var x: String?
    var y: String?
    var zIndex: String?
    var zoom: String?
}

@Deprecated("JS only.")
external interface ElementCSSInlineStyle {
    val style: CSSProperties
}